server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
  instance:
    instance-id: rc-service-instance-${random.uuid}
spring:
  application:
    name: ref-clipping-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
logging:
  level:
    ru:
      thirteenth:
        DEBUG
kafka:
  group:
    id: group-id-${random.uuid}
  server: localhost:9092
  consumer:
    auto-offset-reset: earliest
    enable-auto-commit: false

  properties:
    reconnect.backoff.ms: 1000

