server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
  instance:
    instance-id: api-instance-${random.uuid}
spring:
  application:
    name: api
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
logging:
  level:
    ru:
      thirteenth:
        DEBUG
